spring:
  datasource:
    url: jdbc:mysql:///mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

logging:
  level:
    root: warn
    world.moesakura.mall.user.mapper: trace
  pattern:
    console: "%p%m%n"